broadinstitute/push-to-cloud-service

.github/workflows/pr-test.yml
README.md
deps.edn
src/start.clj
src/util.clj
test/start_test.clj
test/util_test.clj

- https://broadinstitute.atlassian.net/jira/software/projects/GH/boards/530?selectedIssue=GH-749
Ordered by commit time:
- Connect to VPN
- Run `bash ./ops/build.sh` to build the JAR from the root.
- `export environment=dev` and then:
- Run `java -jar target/push-to-cloud-service.jar`

Implement the daemon process

---

src/ptc/start.clj
src/ptc/util/misc.clj
test/data/test_msg_diff_id.edn
test/data/test_msg_same_id.edn
test/ptc/unit/start_test.clj
test/ptc/unit/util_test.clj

- https://broadinstitute.atlassian.net/browse/GH-864
- No changes.

GH-864: Fix JMS parsing.

---

deps.edn
src/ptc/start.clj
src/ptc/util/jms.clj
test/ptc/integration/integration_test.clj
test/ptc/integration/jms_test.clj

- https://broadinstitute.atlassian.net/browse/GH-865
- No changes.

GH-865: Drive JMS queues for testing and so on.

---

in/unit/push-to-cloud.service.in

Implement EnvironmentFile config for the systemd service.
Added EnvironmentFile setting to unit file.

environment file for service

---

test/ptc/acl/permission_test.clj

- I used a wrong bucket to run acl against previously.
- No changes.
- Run `clojure -A:test acl`

Fix the bucket acl is testing against.

---

src/ptc/start.clj

- Bucket needs to be different based on https://github.com/broadinstitute/gotc-deploy/blob/master/deploy/gotc-dev/terraform/global_vars.tf#L50

Use correct bucket

---

src/ptc/util/jms.clj

The cloudfn that is triggered by file uploads to the arrays input bucket will check that all files listed in `ptc.json` have been uploaded before creating a new Arrays workflow. Currently this does not list the `params.txt` file that PTC constructs. In addition, the cloudfn just uses whatever is in the first notifications item as the [payload for the WFL request](https://github.com/broadinstitute/wfl/blob/master/cloud_function/main.py#L56), so this currently fails because it is missing the required `params_file` key.
Add `params_file` key to ptc.json contents 

[GH-890] Add params_file key to ptc.json

---

in/unit/push-to-cloud.service.in

[GH-893] fix typo in unit file

---

test/ptc/e2e/system_test.clj

- Doubles the timeout in the e2e test.

Double the timeout

---

src/ptc/util/jms.clj
src/ptc/util/misc.clj

Fixes: https://broadinstitute.atlassian.net/browse/GH-936
Construct the extended_chip_manifest_file from the `cloudChipMetaDataDirectory` and the `extendedIlluminaManifestFileName`.

[GH-936] Fix extended_chip_manifest file

---

.github/workflows/pr-test.yml
.github/workflows/release.yml

- https://broadinstitute.atlassian.net/browse/GH-1009
- Use the new environment files
- This should result in no new test failures (this is a no-op change)

[GH-1009] Change to environment files

---

.github/workflows/release.yml

- Just changes the help text that'll show when we run this manually

Note that the release note is a path

---

test/data/plumbing-test-jms-dev.edn

- https://broadinstitute.atlassian.net/browse/GH-1027
- Use the path from George. He specifically said we were all good to play with this file in dev environments/PTCs/WFLs/Cromwells (obviously not change it I assume but we don't need to worry as much about it being private)
- Also end the file with a newline
- Uh we can't really test this until we put it dev. I checked that the file he linked to exists and that Cromwell's dev SA specifically has viewer access to the bucket.

[GH-1027] Use a real MAF file

---

src/ptc/util/jms.clj
src/ptc/util/misc.clj
test/ptc/integration/integration_test.clj
test/ptc/tools/gcs.clj
test/ptc/unit/util_test.clj

https://broadinstitute.atlassian.net/browse/GH-1102
Google has been giving us lots of 503s, resulting in partial uploads and PTC failures.
In the case of getting these errors, we should retry.
I don't know how to test this.

[GH-1102] retry on 503

---

src/ptc/util/jms.clj

https://broadinstitute.atlassian.net/browse/GH-1111
Change the upload location from `<input_bucket>/chipName/chipWellBarcode/analysisCloudVersion` to `<input_bucket>/environment/chipName/chipWellBarcode/analysisCloudVersion`

[GH-1111] Add environment from JMS message to cloud-prefix

---

src/ptc/util/jms.clj
test/data/plumbing-test-jms-dev.edn

https://broadinstitute.atlassian.net/browse/GH-1119
Pass the `vaultTokenPath` from the JMS message to support processing staging mercury messages with the dev WFL environment.

[GH-1119] Include vault path in ptc.json

---

README.md

- https://broadinstitute.atlassian.net/browse/GH-1420
- Added a link to the runbook to the README.md.
- Verify the runbook link works?

GH-1420: Link to the PTC section of the runbook.

---

src/ptc/util/jms.clj
src/ptc/util/misc.clj
test/ptc/integration/jms_test.clj
test/ptc/tools/jms.clj
test/ptc/unit/jms_test.clj

- See https://broadinstitute.slack.com/archives/CTUD7J18A/p1622739649003800

Introduce a new PTC lookup mechanism for AoU reprocessing

---

test/ptc/e2e/system_test.clj

Fix the End to End test.

---

README.md
deps.edn
resources/log4j2.xml
src/ptc/util/jms.clj
src/ptc/util/misc.clj
test/data/bad-jms.edn
test/data/good-jms.edn
test/data/reprocessing-jms.edn

- https://broadinstitute.atlassian.net/browse/GH-1554
- https://broadinstitute.atlassian.net/browse/GH-1556
- Updated dependencies then fixed what broke.
- Treat control sample fields as `::copy` rather than `::chip`.

GH-1554: Fix log4j dependency and control sample handling.
