broadinstitute/push-to-cloud-service

README.md
ops/build.sh
ops/deploy.sh

[We want to automate deployment of PTC on prem](https://broadinstitute.atlassian.net/browse/GH-770).
By adding the script, I've been able to write the jenkins build/deploy job in dsp-jenkins. We can complete this implementation later.
- Add mock deploy script. This tests that the .jar file is in the expected location and then errors because it's not clear to me what deployment means yet.
- Change build to not use the class path cache. this causes failures when building in docker as the libraries downloaded in build are deleted leaving the cache stale (note that dependencies are added to the uberjar)
This change is just to facilitate https://github.com/broadinstitute/dsp-jenkins/pull/398

Add deployment script for jenkins automation

---

.gitignore
README.md
deps.edn
ops/build.sh

https://broadinstitute.atlassian.net/browse/GH-810
When generating the .jar build artifact, we should run the unit tests, the outcome of which should affect the result of the build.
Change `ops/build.sh` to run tests on build.
Added a number of flags to customise behaviour. In particular classpath cashing dramatically speeds up builds.
Puzzle:
It's not clear how to make `clojure` use a different `cache_dir` than `.cpcache`. Simply setting `CLJ_CACHE=/path/to/cache` doesn't work as `deps.edn` exists (see https://clojure.org/reference/deps_and_cli#_directories for more info)

alter build script to run tests on build

---

deps.edn
project.clj

Rex noted that we no longer need an empty `project.clj` now that [the bug`cljfmat` has been squished.](https://github.com/weavejester/cljfmt/issues/192)
bump `cljfmat` dependency to 0.6.8
delete `project.clj`

remove empty project.clj

---

.github/workflows/release.yml
.gitignore

Create github workflow to build, test and release push-to-cloud-service.
A release is a tagged commit that:
- has been marked as a release candiate
- has been release noted (propose docs/release/VERSION/changelog.md as the directory for this)
- has been built, tested adn then tagged by this workflow.
Input arguments:
ref: the commit-ish to use/tag
version: the semantic version to release as
release_note: the path/to/changelog.md for this release
draft: manually publish the release - don't do it automatically.

create release workflow

---

deps.edn

- https://broadinstitute.atlassian.net/browse/GH-859
- We don't like errant warning messages and setting this option removes one.
- This is the PTC incarnate of [this WFL PR](https://github.com/broadinstitute/wfl/pull/75)
- Set the jar to multi-release so Log4j2 is happier and doesn't print a warning
- `clojure -A:build` followed by `java -jar target/push-to-cloud-service.jar` doesn't print a warning message complaining about a reflection issue
- Granted, PTC doesn't have help text so the above will absolutely spew exceptions onto your console, but the first line shouldn't complain about a reflection issue anymore

[GH-859] Set jar to multi-release to remove a warning message

---

.github/workflows/release.yml

I broke the release pipeline in https://github.com/broadinstitute/push-to-cloud-service/commit/807b0c3bc7c84ba27c5cd9f2fb928993a74f00d3
Fix syntax error 
Sadly I can't test this in a fork as I don't have the necessary secrets to run the tests.

fix syntax error in release.yaml

---

src/ptc/util/jms.clj
test/ptc/integration/integration_test.clj
test/ptc/integration/jms_test.clj
test/ptc/tools/gcs.clj
test/ptc/unit/start_test.clj
test/ptc/unit/util_test.clj
tests.edn

PTC should only be using `gsutil` to communicate with GCS. Right now, there's a module `gcs` that makes https requests with custom auth headers. We probably shouldn't ship this.
Move `ptc.util.gcs` into a test namespace so it can be used in testing code.
Remove knowledge of `gcs` from product code.

remove gcs http requests fom product code

---

in/install.sh.in
in/unit/push-to-cloud.service.in

The EnvironmentFile does not function as I thought it did.  Use of EnvironmentFile is actually discouraged. The runas user is now hard coded as "ptc".  This user will be created as part of the rpm creation.
Remove EnvironmentFile config and hard code runas user to "ptc".  
Also changed case of Restart specifier.

hard code runas user

---

deps.edn
resources/log4j2.xml
src/ptc/start.clj
src/ptc/util/jms.clj
src/ptc/util/misc.clj
test/data/test_msg_diff.edn
test/data/test_msg_same.edn
test/ptc/integration/integration_test.clj
test/ptc/integration/jms_test.clj
test/ptc/tools/gcs.clj
test/ptc/unit/start_test.clj
test/ptc/unit/util_test.clj
tests.edn

- https://broadinstitute.atlassian.net/browse/GH-881
- Let PTC push-to-cloud by default. Also teach it to read bucket from env var.
- Move the `gs-url` from the deprecated `gcs` module to the `misc` module.
- Functions in `start` module now accepts a new `push-to` gs-url argument.
- Update/fix some tests.
- Revert some changes @tbl3rd has done:
- `peek-message` should not block but rather sleep and wake each loop, since the queue browser is a immutable snapshot.
- re-implement a message comparator so timestamps and memory addresses won't break message comparison.
- `clojure -m ptc.start` and in a separate process, run `clojure -A:queue 2` as you wish.

[GH-881] Let PTC push-to-cloud by default

---

in/unit/push-to-cloud.service.in

In this change, I'm setting a re-start policy for the `systemd` unit before a human has to manually start the service.
The unit will *always* restart unless it has failed 3 times within 5 minutes.
The unit will be restarted in 1 minute intervals.
I'm making this PR separate to the code changes as I'm applying them on-top of https://github.com/broadinstitute/push-to-cloud-service/pull/32.

[GH-893] restart policy: max 3 fails in 5 minutes in 1 minute intervals

---

deps.edn
src/ptc/start.clj
src/ptc/util/misc.clj
test/ptc/acl/permission_test.clj
test/ptc/e2e/system_test.clj
test/ptc/integration/integration_test.clj
test/ptc/integration/jms_test.clj
test/ptc/tools/cromwell.clj
test/ptc/tools/gcs.clj
test/ptc/tools/jms.clj
test/ptc/tools/wfl.clj
test/ptc/unit/start_test.clj

Purpose
As suggested by Tom, we shouldn't use vault to store stuff that isn't secret.
In this PR, PTC no longer looks for the queue name and url in vault in favour of using the following environment variables (to be configured in `/etc/sysconfig/push-to-cloud`):
`ZAMBONI_ACTIVEMQ_QUEUE_NAME`: The name of the queue to poll
`ZAMBONI_ACTIVEMQ_URL`: The url of the ActiveMQ server
`ZAMBONI_ACTIVEMQ_SECRET_PATH`: The vault path to the username/password secret. This was previously computed from the "environment". We don't need these in PTC.
These variables are changed and the vault is read once at start-up so that we don't get connection failures later on (previously it called with-push-to-cloud-jms-connection which did a vault read in the main loop).
There's also the `PTC_BUCKET_URL` variable …

[GH-862] Remove ActiveMQ Non-secrets

---

src/ptc/start.clj

As discussed, we need to make sure PTC doesn't keep trying to loop forever. This was as simple as removing a while true loop.
Now if the message loop throws, PTC will exit with a non-zero exit code.

[GH-893] let ptc die - don't loop forever

---

test/ptc/tools/jms.clj

Addresses ticket https://broadinstitute.atlassian.net/browse/GH-900
Use a test message that references on-prem data so that PTC does not hang/crash when trying to copy the files.
Note: If you queue multiple messages at the same time (e.g. `clojure -A:queue 3 "dev"`), they will all be identical. I didn't change it because I don't think queuing multiple messages at the same time is currently required by any of our testing.

[GH-900] Update queue alias test message

---

test/ptc/e2e/system_test.clj
test/ptc/tools/gcs.clj
test/ptc/tools/jms.clj

- Recurs based on `gsutil stat` having an exception rather than on parsing `gsutil ls` output.
- Reworks the test a tiny bit to no longer test the output of `gsutil ls` but rather the fact that everything could be `stat`ed with issue
- Make the "sleep" text a bit more useful so we can diagnose issues
- This makes e2e pass consistently, you can try it locally.

Recur based on exceptions rather than string parsing

---

README.md
test/ptc/e2e/system_test.clj
test/ptc/tools/jms.clj

https://broadinstitute.atlassian.net/browse/GH-909
- Pass in specific environment variables to the e2e test instead of mapping based on an "environment" 
- Make the test default to dev
Note: This will require updating both Jenkins jobs that run the e2e test.

[GH-909] Fix test environment variables

---

test/data/reprocessing-jms.edn
test/ptc/integration/integration_test.clj
test/ptc/integration/jms_test.clj

Ticket: https://broadinstitute.atlassian.net/browse/GH-949
- Change the output bucket to `broad-gotc-dev-wfl-ptc-test-outputs` which has a lifecycle policy that will delete all of that bucket's contents each day.
- Change the input bucket to `broad-gotc-dev-wfl-ptc-test-inputs`, which will be the new centralized location for all of the PTC & WFL test input files.

[GH-949] Update test buckets

---

src/ptc/util/jms.clj
src/ptc/util/misc.clj

Ticket: https://broadinstitute.atlassian.net/browse/GH-981
Use the content-md5 header with gsutil cp so that it will validate the file checksum before making it visible/accessible in the bucket: https://cloud.google.com/storage/docs/gsutil/commands/cp#checksum-validation

[GH-981] Use content-md5 header with gsutil cp

---

src/ptc/util/jms.clj
test/data/plumbing-test-jms-dev.edn

Ticket: https://broadinstitute.atlassian.net/browse/GH-1015
If a `minorAlleleFrequencyFileCloudPath` is in the JMS message, copy that file path to ptc.json under the key `minor_allele_frequency_file`.

[GH-1015] Add minor_allele_frequency_file to ptc.json

---

.github/workflows/pr-test.yml
.github/workflows/release.yml
test/ptc/tools/wfl.clj
tests.edn

- https://broadinstitute.atlassian.net/browse/GH-1083
- This PR is made as I'm investigating and just for the sake of "FIXING IT", it does not represent the best solution of "IMPROVING IT". AFAICT, now since WFL supports filter by workload UUID, it **might** be better if the test can further filter on project name ©eated by the cloud function) so the test can run a bit faster.

[GH-1083] Fix the ptc-wfl e2e test

---

src/ptc/util/misc.clj
test/ptc/unit/util_test.clj

- https://broadinstitute.atlassian.net/browse/GH-1066
- I grabbed the `do-or-nil-silently` function from WFL and used that instead of `do-or-nil` that explicitly prints output
- Added a test for the `gcs-object-exists?` to make sure it still works and is now silent
- Check the unit tests

[GH-1066] Swallow `gsutil stat` errors better

---

src/ptc/util/jms.clj
test/data/plumbing-test-jms-dev.edn

- https://broadinstitute.atlassian.net/browse/GH-1042
- Pass `environment` along if it exists
- Not required because WFL doesn't require it
- I can't really think of any. We hit the same testing issue with `minor_allele_frequency_file`, the copying behavior in PTC isn't exposed for testing, it sorta just works. I'd rather not reinvent the wheel here--that'd be a lot of refactoring and test writing to make sure the refactoring didn't break anything. Maybe that's a future ticket, I dunno.
- This is just like #53 which is known-working

[GH-1042] Pass environment along

---

src/ptc/util/jms.clj

https://broadinstitute.atlassian.net/browse/GH-1108
The object names in google cloud storage are case-sensitive, so the `environment` in the JMS message should be lower-cased to ensure we only end up with one `staging/...` object in the bucket.

[GH-1108] Make cloud-prefix env lowercase

---

deps.edn
test/data/plumbing-test-jms-dev.edn
test/ptc/e2e/system_test.clj

- https://broadinstitute.atlassian.net/browse/GH-1146
- Use a real dev token for the testing JMS message.
- Correct the order of the testing assertions so it works like: `(= Expected Actual)`.
- Why it didn't fail before? Because WFL used to have a default value for this field, as it's always `dev` in the past. Now WFL starts to use the value from this field to override its own default one! Check [here](https://github.com/broadinstitute/wfl/commit/5b53b8b0a74e305752767fcf0e47b340bb2cf0da#diff-4cb7e9e206a00497d94cf3e30972efa1e5e2472df4c308021988be535614503a) for details.

[GH-1146] Fix the e2e tests in dev.

---

test/ptc/e2e/system_test.clj

Double the timeout for the test

Doubling timeout to see if it passes workflow test more often

---

test/ptc/tools/wfl.clj

RR: https://broadinstitute.atlassian.net/browse/GH-1384
Caused by changes to workflow-launcher's API where workflows are no
longer returned with the workload. Fix was to call the new workflows
endpoint to fetch them.

[GH-1384] Fix End-to-End Test Failure

---

README.md
test/ptc/acl/permission_test.clj
test/ptc/acl/production_permission_test.clj
tests.edn

- https://broadinstitute.atlassian.net/browse/GH-1351
- Maybe ^:exclude the ACL test.
- Retained because it does add some value to the e2e test.
- It verifies the the ACL is restricted enough to forbid just anyone from reading the buckets, for example.
- Please look this over and let me know what you think.
- There are now several obstacles to running this test by mistake.
- It now has `production` in its name.
- It is `:excluded` by default.
- It fails with a warning message unless it is edited to enable the test.
- Do we want to keep this test or just delete it?
- If we want to keep it, how many of these obstacles should we retain?
- Can you think of a better way?

Maybe ^:exclude the ACL test.

---

README.md
src/ptc/start.clj
src/ptc/util/misc.clj
test/ptc/e2e/system_test.clj
test/ptc/integration/integration_test.clj

- Redirect messages to dead letter queue on exception.
Question:
I added a new ENV `ZAMBONI_ACTIVEMQ_DEAD_LETTER_QUEUE_NAME`, but cannot be able to find where it's configured for deployment, does any one know where does `push-to-cloud.config` live?

Redirect messages to dead letter queue on exception.

---

resources/log4j2.xml
src/ptc/util/jms.clj
test/data/bad-jms.edn
test/data/good-jms.edn
test/data/plumbing-test-jms-dev.edn
test/data/reprocessing-jms.edn
test/ptc/e2e/system_test.clj
test/ptc/tools/cromwell.clj
test/ptc/tools/wfl.clj

- https://broadinstitute.atlassian.net/browse/GH-1536
- Fix the system end-to-end test in dev.
- Find chip metadata in `cloudChipMetaDataDirectory`.
- Fix cast exception because Cromwell evidently requires `Content-type` now.
- Extend timeout when waiting for workflow creation.
- The interesting changes are in `test/ptc/e2e/system_test.clj` and `test/ptc/tools/cromwell.clj`.
- Also replaced bogus `gs://storage/` URLs with real GCS folders containing the chip metadata.

Fix the AoU/PtC end-to-end test in development.

---

deps.edn

- https://broadinstitute.atlassian.net/browse/GH-1559
This newer version of log4j goes further than 2.15.0 in preventing attacks. 
https://broadinstitute.slack.com/archives/CADU7L0SZ/p1639519922167700
Previously, we bumped to 2.15.0 in this PR: https://github.com/broadinstitute/push-to-cloud-service/pull/77

GH-1559 Upgrade PtC log4j to 2.16.0

---

deps.edn

- https://broadinstitute.atlassian.net/browse/GH-1561
This newer version of Log4J helps guard against DOS attacks.
Previous version bump: https://github.com/broadinstitute/push-to-cloud-service/pull/78

GH-1561 Upgrade PTC Log4J to 2.17.0
